apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_KEY_ID: QUtJQVZWNU9QR1NCSTZTSVU3VEk=
  AWS_SECRET_KEY: aktYMWt6RFJZUHhRTEsrSVFTNTg2Mk9CN25ud3NjK3FFMDZEQmZ6eQ==
  AWS_REGION: dXMtZWFzdC0x
  BUCKET_NAME: bWFuYWdlZGNsb3VkLWRldi1kZi1wbGF0Zm9ybS1zdG9yYWdlLWJ1Y2tldA==
