apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: webrtc-test1-differ-nodes-with-turn
  name: turn
  labels:
    app.kubernetes.io/name: turn
    app.kubernetes.io/instance: turn
    app.kubernetes.io/version: 0.0.1
spec:
  selector:
    matchLabels:
          app.kubernetes.io/name: turn
          app.kubernetes.io/instance: turn
          app.kubernetes.io/version: 0.0.1
  template:
    metadata:
      labels:
            app.kubernetes.io/name: turn
            app.kubernetes.io/instance: turn
            app.kubernetes.io/version: 0.0.1
    spec:
      hostNetwork: true
      nodeSelector:
        # Node group 1 label and value
        nodegroup: turn0
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 1000
      containers:
        - name: turn
          image: coturn/coturn
          imagePullPolicy: Always
          ports:
            # - name: turn-udp
            #   containerPort: 3000
            #   protocol: UDP
            - name: turn-udp
              containerPort: 3478
              hostPort: 3478
              protocol: UDP
            - name: turn-tcp
              containerPort: 3478
              hostPort: 3478
              protocol: TCP
          # securityContext:
          #   capabilities:
          #     drop:
          #       - ALL
            # readOnlyRootFilesystem: true
            # allowPrivilegeEscalation: false
          args:
          #   - --stun-only
            - -v

--- 

apiVersion: v1
kind: Service
metadata:
  name: turn
  namespace: webrtc-test1-differ-nodes-with-turn
  labels:
       app.kubernetes.io/name: turn
       app.kubernetes.io/instance: turn
       app.kubernetes.io/version: 0.0.1
spec:
  type: ClusterIP
  ports:
    # - port: 3000
    #   targetPort: 3000
    #   protocol: UDP
    #   name: turn-udp
    - port: 3478
      targetPort: 3478
      protocol: UDP
      name: turn-udp
    - port: 3478
      targetPort: 3478
      protocol: TCP
      name: turn-tcp
    # - port: 3478
    #   targetPort: 3478
    #   protocol: TCP
    #   name: turn-port3
    # - port: 3479
    #   targetPort: 3479
    #   protocol: TCP
    #   name: turn-port4
  selector:
       app.kubernetes.io/name: turn
       app.kubernetes.io/instance: turn
       app.kubernetes.io/version: 0.0.1